import { TodoContextProvider } from "@/store/todos";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TodoProvider from "@/provider/TodoProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TODO TASK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TodoContextProvider>
          <TodoProvider>
            {children}
          </TodoProvider>
        </TodoContextProvider>
      </body>
    </html>
  );
}
